services:
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: youlearn
            MYSQL_USER: youlearn
            MYSQL_PASSWORD: youlearn
        ports:
            - "3301:3306"
        volumes:
        - my-db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "8091:80"
        depends_on:
            - mysql
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "8087:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network
    php:
        image: php:8.2-fpm
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
networks:
  app-network:
    driver: bridge
volumes:
    my-db: