# The tenancy's object-storage namespace, which is also the OCIR namespace.
# Looking it up removes a value that otherwise has to be found in the console
# and pasted in by hand.
data "oci_objectstorage_namespace" "this" {
  compartment_id = var.oci_tenancy_ocid
}

/**
 * What you need after `terraform apply`.
 *
 * The two DNS records are the first thing to set — Let's Encrypt cannot issue a
 * certificate until both names resolve to the instance.
 */

output "instance_public_ip" {
  description = "Reserved public IP. Point both DNS A records here."
  value       = oci_core_public_ip.app.ip_address
}

output "dns_records" {
  description = "The A records to create at your DNS provider."
  value = (var.app_domain == null || var.auth_domain == null
    ? { "set app_domain and auth_domain in terraform.tfvars" = oci_core_public_ip.app.ip_address }
    : {
      (var.app_domain)  = oci_core_public_ip.app.ip_address
      (var.auth_domain) = oci_core_public_ip.app.ip_address
  })
}

output "ssh_command" {
  description = "How to reach the instance."
  value       = "ssh -i ~/.ssh/youlearn ubuntu@${oci_core_public_ip.app.ip_address}"
}

/* -----------------------------------------------------------------------------
 * Generated database passwords
 *
 * The databases are containers on the instance, reachable only over the
 * compose network — they publish no port and nothing outside the host can
 * connect to them. The passwords are still generated rather than chosen, so
 * they are long, unique per environment, and never typed anywhere.
 * -------------------------------------------------------------------------- */

resource "random_password" "mysql_root" {
  length           = 32
  special          = true
  override_special = "!#%*_-+"
}

resource "random_password" "mysql_app" {
  length           = 32
  special          = true
  override_special = "!#%*_-+"
}

resource "random_password" "keycloak_db" {
  length           = 32
  special          = true
  override_special = "!#%*_-+"
}

resource "random_password" "rate_limit_pepper" {
  length  = 40
  special = false
}

/* --------------------------------------------------------------- app config -- */

output "env_file" {
  description = <<-EOT
    The .env for docker-compose.prod.yml, ready to copy to the instance:

      terraform output -raw env_file > .env
      scp -i ~/.ssh/youlearn .env ubuntu@<ip>:/opt/youlearn/.env

    Only the Keycloak bootstrap password needs filling in by hand. The domains
    come from terraform.tfvars; the OCIR namespace is looked up.
  EOT
  sensitive   = true
  value       = <<-EOT
    # Generated by terraform. Contains credentials — never commit this.

    OCI_REGISTRY=ocir.${var.oci_region}.oci.oraclecloud.com
    OCI_NAMESPACE=${data.oci_objectstorage_namespace.this.namespace}
    KEYCLOAK_REPO=youlearnkeycloak
    API_REPO=youlearnapi
    IMAGE_TAG=latest

    WEB_ORIGIN=${var.app_domain == null ? "SET_app_domain_IN_TFVARS_THEN_RERUN_APPLY" : "https://${var.app_domain}"}
    KEYCLOAK_PUBLIC_URL=${var.auth_domain == null ? "SET_auth_domain_IN_TFVARS_THEN_RERUN_APPLY" : "https://${var.auth_domain}"}

    # --- databases (containers on this host, no published ports) ---
    MYSQL_ROOT_PASSWORD=${random_password.mysql_root.result}
    MYSQL_PASSWORD=${random_password.mysql_app.result}
    KEYCLOAK_DB_PASSWORD=${random_password.keycloak_db.result}

    # --- Keycloak ---
    # First boot only. Create a real administrator, then delete this and redeploy.
    KEYCLOAK_ADMIN_USER=admin
    KEYCLOAK_ADMIN_PASSWORD=TODO_choose_a_strong_password
    # Keycloak generates this on first realm import. Read it back with
    # scripts/read-client-secrets.sh, then set it here and restart the api.
    KEYCLOAK_ADMIN_CLIENT_SECRET=TODO_after_first_boot

    # --- api ---
    RATE_LIMIT_PEPPER=${random_password.rate_limit_pepper.result}
    # Caddy's address on the compose network, so the API records the real
    # caller's IP rather than the proxy's.
    TRUSTED_PROXIES=
  EOT
}
